# This is used by the action https://github.com/dorny/paths-filter
docker: &docker
  - added|modified: './docker/**'

dependencies: &dependencies
  - 'pdm.lock'
  - 'pyproject.toml'

python: &python
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

docker_base:
  - added|modified: *docker
  - *dependencies

run_tests:
  - added|modified: *python
  - 'pytest.ini'

migrations:
  - added|modified: 'src/**/migrations/*'

lint:
  - added|modified: *python
  - '.flake8'
  - 'pyproject.toml'