# This is used by the action https://github.com/dorny/paths-filter
docker_base:
  - added|modified: './docker/**'
  - 'pdm.lock'
  - 'pyproject.toml'

dependencies:
  - 'pdm.lock'

run_tests:
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'pytest.ini'

python:
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'manage.py'

migrations:
  - added|modified: 'src/**/migrations/*'
