# This is used by the action https://github.com/dorny/paths-filter
docker_base:
  - added|modified: './docker/**'
  - 'pdm.toml'
  - 'pyproject.toml'

run_tests:
  - added|modified: 'src/**'
  - added|modified: 'tests/**'
  - 'pytest.ini'

python:
  - added|modified: 'src/**/*.py'
  - added|modified: 'tests/**/*.py'
  - 'manage.py'