[tool.poetry]
name = "trash"
version = "0.1.0"
description = ""
authors = ["sax <s.apostolico@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
tox = "*"
django="*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
