[tool.poetry]
name = "trash"
version = "0.31.0"
description = "description"
readme = "README.rst"
authors = ["sax <s.apostolico@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
tox = "*"
django="*"
pytest="*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
