# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Calculate Release Hash'
description: 'Calculate deps and os hash'
inputs:
  files:
    description: 'Files to use to calculate the hash'
    required: true
    default: "pdm.lock docker/bin/* docker/conf/* docker/Dockerfile"
  debug:
    description: 'debug'
    required: false
    default: false

outputs:
  CHECKSUM:
    description: 'CHECKSUM'
    value: ${{ steps.run.outputs.CHECKSUM }}
  BUILD_DATE:
    description: 'BUILD_DATE'
    value: ${{ steps.run.outputs.BUILD_DATE }}
  SOURCE_COMMIT:
    description: 'SOURCE_COMMIT'
    value: ${{ steps.run.outputs.SOURCE_COMMIT }}
  VERSION:
    description: 'VERSION'
    value: ${{ steps.run.outputs.VERSION }}
  GITHUB_SERVER_URL:
    description: 'GITHUB_SERVER_URL'
    value: ${{ steps.run.outputs.GITHUB_SERVER_URL }}
  GITHUB_REPOSITORY:
    description: 'GITHUB_REPOSITORY'
    value: ${{ steps.run.outputs.GITHUB_REPOSITORY }}

runs:
  using: 'composite'
  steps:
    - id: checksum
      uses: ./.github/actions/checksum
      with:
        files: ${{ inputs.files }}
    - id: commit
      uses: ./.github/actions/last_commit
    - id: run
      shell: bash
      run: |
        build_date=$(date +"%Y-%m-%d %H:%M")
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        ver="${branch/\//-}"

        echo "CHECKSUM=${{ steps.checksum.outputs.checksum }}" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=${build_date}" >> $GITHUB_OUTPUT
        echo "SOURCE_COMMIT=${{ steps.commit.outputs.last_commit_sha }}" >> $GITHUB_OUTPUT
        echo "VERSION=${ver}" >> $GITHUB_OUTPUT
        echo "GITHUB_SERVER_URL=${{ github.server_url }}" >> $GITHUB_OUTPUT
        echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_OUTPUT
    - name: dump
      if: ${{ inputs.debug == 'true' }}
      shell: bash
      run: |
        echo "${{ toJSON( steps.run.outputs) }}"
