# ref: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
name: 'Calculate version hash'
description: 'Calculate deps and os hash'
inputs:
  files:
    description: 'Files to use to calculate the hash'
    required: true
    default: "pdm.lock docker/bin/* docker/conf/* docker/Dockerfile"
outputs:
  hash: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.calc.outputs.hash }}

runs:
  using: 'composite'
  steps:
    - name: Calculate Release Hash
      id: calc
      shell: bash --noprofile --norc -eo pipefail -ux {0}
      run: |
        LOCK_SHA=$(sha1sum ${{ inputs.files }} | sha1sum | awk '{print $1}' | cut -c 1-8)
        echo "Release Hash on: ${{ inputs.files }} is $LOCK_SHA"
        echo "hash=$LOCK_SHA" >> "$GITHUB_OUTPUT"
