name: Run Tests

on:
    push:
      branches:
      - develop
      - releases/*
      - master/*

env:
  DOCKER_DEFAULT_PLATFORM: linux/amd64

jobs:

  files-changed:
    name: check files
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      test_files: ${{ steps.changes.outputs.run_tests }}
      docker_files: ${{ steps.changes.outputs.docker_base }}
      python_files: ${{ steps.changes.outputs.python }}
    steps:
      - run: git config --global --add safe.directory $(realpath .)
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: changes
        name: Check for backend file changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  build:
    name: Build Image
    uses: ./_build.yml
    with:
      force: false
      tags: []