name: "[DEBUG] Echo"

on:
  check_run:
  create:
  delete:
  discussion:
  discussion_comment:
  fork:
  issues:
  issue_comment:
  milestone:
  pull_request:
  pull_request_review_comment:
  pull_request_review:
  push:
  release:
  workflow_dispatch:

jobs:
  printJob:
    if: ${{ contains(github.event.head_commit.message, 'ci:debug') }}
    name: "[DEBUG] Echo Event"
    runs-on: [ubuntu-latest, self-hosted]
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        VARS_CONTEXT:  ${{ toJson(vars) }}
      run: |
        cat <<EOF
        ======= ${{ github.event_name }} : ${{ github.event.action }}  ===========
        -- context ------------------------------------        
        $GITHUB_CONTEXT"
        -- vars ---------------------------------------        
        $VARS_CONTEXT"
        ===============================================
        EOF 
        
