name: Lint iSort
on:
#  push:
#    branches:
#      - develop
#      - master
#      - staging
#      - releases/*
  pull_request:
    branches: [develop, master]
    types: [synchronize, opened, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install isort
      - name: iSort
        run: isort src/ --check-only
