#on:
#  push:
#    tags:
#      - 'v*'
#env:
#  DOCKER_IMAGE_DEV: ${{ vars.DOCKERHUB_ORGANIZATION }}/${{ vars.DOCKER_CACHE_IMAGE }}-dev
#
#jobs:
#  build-and-push:
#    runs-on: ubuntu-20.04
#    timeout-minutes: 3
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: DockerHub login
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - name: Build and push
#      uses: docker/build-push-action@v5
#      with:
#        push: true
#        image: ${DOCKER_IMAGE_DEV}
#
##    - name: build and push image
##      uses: docker/build-push-action@v4
##      with:
##        context: .
##        username: ${{ secrets.DOCKER_USERNAME }}
##        password: ${{ secrets.DOCKER_PASSWORD }}
##        repository: {{ vars.DOCKERHUB_ORGANIZATION }}/${{ vars.DOCKER_CACHE_IMAGE }}
##        registry: ${{ secrets.DOCKER_REGISTRY }}
##        tag_with_ref: true