name: "[DEBUG] Tag"

on:
  create:
      tags:

jobs:
  dump:
    name: "[DEBUG] Echo Full Context"
#    if: ${{ contains(github.event.head_commit.message, 'ci:debug') }}
    runs-on: self-hosted
    steps:
      - name: Echo
        run: |
          echo "::group:: "
          echo "::notice:: github.ref:                         ${{github.ref}}"  # tag path
          echo "::notice:: github.sha:                         ${{github.run_id}}"  # sha
          echo "::notice:: github.run_number:                  ${{github.run_number}}"
          echo "::notice:: github.event.master_branch          ${{github.event.master_branch}}"  # source branch
          echo "::notice:: github.event.ref                    ${{github.event.ref}}"  # tag name
          echo "::notice:: github.event.pull_request.head.ref  ${{github.event.pull_request.head.ref}}"
          echo "::notice:: github.event.pull_request.html_url  ${{github.event.pull_request.html_url}}"
          echo "::endgroup::"
