name: "Build Distro"
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true


jobs:
  trivy:
    name: Check Image with Trivy
    runs-on: ubuntu-latest
    needs: [ deployable ]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{needs.deployable.outputs.image}}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
