name: Delete merged releases
on:
  pull_request:
    types:
#      - opened
      - closed
#      - edited
#      - reopened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete merged branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: 13,22,33
          prefix: "release/"
          numbers: ${{github.event.pull_request.number}}
