name: Dump Env vars

on:
  pull_request:
    types:
      - closed

jobs:
  one:
    if: ${{ contains(github.event.head_commit.message, 'ci:debug') }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Env vars
        run: |
            echo "====== ENVIRONMENT ================="
            env | sort
            echo "===================================="
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
            echo "====== GITHUB_CONTEXT =============="
            echo "$GITHUB_CONTEXT"
            echo "===================================="
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo "====== JOB_CONTEXT =============="
          echo "$JOB_CONTEXT"
          echo "===================================="
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo "====== STEPS_CONTEXT =============="
          echo "$STEPS_CONTEXT"
          echo "===================================="
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo "====== RUNNER_CONTEXT =============="
          echo "$RUNNER_CONTEXT"
          echo "===================================="
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: |
          echo "====== STRATEGY_CONTEXT =============="
          echo "$STRATEGY_CONTEXT"
          echo "===================================="
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: |
          echo "====== MATRIX_CONTEXT =============="
          echo "$MATRIX_CONTEXT"
          echo "===================================="
