name: Lint Flake8
on:
#  push:
#    branches:
#      - develop
#      - master
#      - staging
#      - releases/*
  pull_request:
    branches: [develop, master]
    types: [synchronize, opened, reopened, ready_for_review]

defaults:
  run:
    shell: bash


permissions:
  contents: read

jobs:
  changes:
    id: changes
    name: check files
    runs-on: [ubuntu-latest, self-hosted]
    timeout-minutes: 3
    outputs:
      lint: ${{ steps.changes.outputs.lint }}
  flake8:
    needs: changes
    runs-on: [ubuntu-latest, self-hosted]
    if: github.event.pull_request.draft == false && steps.changes.outputs.lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        # Stop the build if there are Python syntax errors or undefined names
        run: flake8 src/ --count --statistics --max-line-length=127

      - name: Warnings
        run: flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-exclude=""
  isort:
    needs: changes
    runs-on: [ubuntu-latest, self-hosted]
    if: github.event.pull_request.draft == false && steps.changes.outputs.lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install isort
      - name: iSort
        run: isort src/ --check-only
  bandit:
    needs: changes
    runs-on: [ubuntu-latest, self-hosted]
    if: github.event.pull_request.draft == false && steps.changes.outputs.lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install isort
      - name: bandit
        run: bandit src/
