name: Release Candidate
on:
  milestone:
#  workflow_run:
#    workflows: ["Run Tests"]
#    branches: ['releases/*']
#    types:
#      - completed

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        uses: ./.github/actions/version
#    runs-on: ubuntu-20.04
#    needs: [ aa]
#    steps:
      - name: Build RC docker
        run: |
          echo "======== ${{ steps.version.outputs.stage }} ==============="
          echo "======== ${{ steps.version.outputs.version }} ==============="
          echo "======== ${{ needs.parent.outputs.hash }} ==============="
          echo "======== ${{ github.ref }} - ${{env.GITHUB_REF_NAME}} - ${GITHUB_REF##*/} ======="
#          version=$(git describe --tags --dirty --always | sed -e 's/^v//')
#          echo "Build release $version"
