name: "Lint mypy"
on:
  push:
    branches:
      - develop
      - master
      - staging
      - releases/*


permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install mypy
      - name: mypy
        run: mypy src/
