name: Python package

on:
    push:
        branches:
            - release/*

jobs:

    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2

            - name: Install requirements
              run:  pip install -e .[dev]

            - name: Check Manifest
              run: check-manifest .

            - name: Build Package
              run: python -m build

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
