name: Release

on:
  pull_request:
    types: [ opened ]

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "::group:: "
          echo "::notice:: github.event_name:                  ${{github.event_name}}" # es. release
          echo "::notice:: github.run_id:                      ${{github.run_id}}"
          echo "::notice:: github.run_number:                  ${{github.run_number}}"
          echo "::notice:: github.event.action                 ${{github.event.action}}"  # es. deleted
          echo "::notice:: github.event.release.draft          ${{github.event.release.draft}}"
          echo "::notice:: github.event.release.prerelease     ${{github.event.release.prerelease}}"
          echo "::notice:: github.event.pull_request.base.ref  ${{github.event.pull_request.base.ref}}"
          echo "::notice:: github.event.pull_request.head.ref  ${{github.event.pull_request.head.ref}}"
          echo "::notice:: github.event.pull_request.html_url  ${{github.event.pull_request.html_url}}"
          echo "::endgroup::"
