name: Merge To Master

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "::group:: "
          echo "::notice:: github.event_name:                  ${{github.event_name}}" # es. release
          echo "::notice:: github.run_id:                      ${{github.run_id}}"
          echo "::notice:: github.run_number:                  ${{github.run_number}}"
          echo "::notice:: github.event.action                 ${{github.event.action}}"  # es. deleted
          echo "::notice:: github.event.release.draft          ${{github.event.release.draft}}"
          echo "::notice:: github.event.release.prerelease     ${{github.event.release.prerelease}}"
          echo "::notice:: github.event.pull_request.base.ref  ${{github.event.pull_request.base.ref}}"
          echo "::notice:: github.event.pull_request.head.ref  ${{github.event.pull_request.head.ref}}"
          echo "::notice:: github.event.pull_request.html_url  ${{github.event.pull_request.html_url}}"
          if [[ "${{contains(github.event.head_commit.message, 'ci:tag=')}}" == "true" ]];then
            TAG=$(echo "ci:tag=1.0rc1" | sed -r 's/.*ci:tag=([0-9a-z.-]*).*/\1/')
          fi
          echo "::endgroup::"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          title: "Backport Master to Develop"
          commit-message: "Backport Master to Develop"
          author: ${{ github.actor }}
          assignees: ${{ github.actor }}
      - name: Create or Update Project Card
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: My project
          column-name: My column
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Tag snapshot
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.TAG }}
