name: Release
on:
  pull_request:
    types:
#      - opened
      - closed
#      - edited
#      - reopened
jobs:
  create_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ncipollo/release-action@v1
        with:
          token: ${{github.token}}

  delete_merged_release_branche:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete merged branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          numbers: ${{github.event.pull_request.number}}
