name: "[DEBUG] Release Candidate"

on:
  pull_request:
#    types: [ opened,closed,reopened,synchronize ]
    branches:
      - 'releases/**'
      - 'rc/**'

jobs:
  my-action:
    runs-on: self-hosted
    steps:
      - name: Echo
        run: |
          is_hotfix="${{contains(github.event.pull_request.head.ref, 'hotfix/')}}"
          is_rc="${{contains(github.event.pull_request.head.ref, 'rc/')}}"          
          target_branch="${{github.event.pull_request.base.ref}}"
          message="${{github.event.head_commit.message}}"

          echo "::group:: "
          echo "::notice:: github.event_name:                  ${{github.event_name}}"
          echo "::notice:: github.ref:                         ${{github.ref}}"
          echo "::notice:: github.sha:                         ${{github.sha}}"
          echo "::notice:: github.run_id:                      ${{github.run_id}}"
          echo "::notice:: github.run_number:                  ${{github.run_number}}"
          echo "::notice:: github.actor:                       ${{github.actor}}"
          echo "::notice:: github.event.action                 ${{github.event.action}}"
          
          echo "::notice:: github.event.pull_request.base.ref  ${{github.event.pull_request.base.ref}}"
          echo "::notice:: github.event.pull_request.head.ref  ${{github.event.pull_request.head.ref}}"
          echo "::notice:: github.event.pull_request.html_url  ${{github.event.pull_request.html_url}}"

          if [[ $target_branch == master && $is_hotfix == true ]]; then
              TAG=$(echo "$message" | sed -r 's/.*ci:tag=([0-9a-z.-]*).*/\1/')
              echo "::warning:: HOTFIX - Create TAG"
          elif [[ $target_branch == master && $is_rc == true ]]; then
              TAG=$(echo "$message" | sed -r 's/.*ci:tag=([0-9a-z.-]*).*/\1/')
              echo "::warning:: RELEASE  - Create TAG"
          elif [[ $target_branch == develop ]]; then
              echo "::warning:: FEATURE  - Do NOT create TAG"
          else
              echo "::warning:: UNKNOWN target $target_branch - Do NOT create TAG"
          fi            
          echo "::notice:: TAG             echo "::endgroup::"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "====== GITHUB_CONTEXT =============="
          echo "$GITHUB_CONTEXT"
          echo "===================================="
#      - uses: actions/checkout@v4
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ env.TAG }}
#          release_name: Release ${{ github.ref }}
##          body:
#          draft: true
#          prerelease: true
