name: "[DEBUG] Tag"

on:
  create:
      tags:

jobs:
  dump:
    name: "[DEBUG] Echo Full Context"
#    if: ${{ contains(github.event.head_commit.message, 'ci:debug') }}
    runs-on: self-hosted
    steps:
      - name: Echo
        run: |
          echo "::group:: "
          echo "::notice:: github.event_name:                  ${{github.event_name}}"
          echo "::notice:: github.run_id:                      ${{github.run_id}}"
          echo "::notice:: github.run_number:                  ${{github.run_number}}"
          echo "::notice:: github.event.action                 ${{github.event.action}}"
          echo "::notice:: github.event.pull_request.base.ref  ${{github.event.pull_request.base.ref}}"
          echo "::notice:: github.event.pull_request.head.ref  ${{github.event.pull_request.head.ref}}"
          echo "::notice:: github.event.pull_request.html_url  ${{github.event.pull_request.html_url}}"
          echo "::endgroup::"
