name: CI

on: push

jobs:
  test:
#    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        django-version: [ 3.1 ]
    env:
      DJANGO_VERSION: ${{ matrix.django-version }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2

#    - name: Install dependencies
#      run: python -m pip install --upgrade pip tox
#
#    - name: Test with tox
#      run: tox -e d${DJANGO_VERSION//.}-py${PYTHON_VERSION//.}

  release:
#    if: github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/release/')
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Merge to master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}

      - name: Merge to develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: develop
          github_token: ${{ github.token }}
