name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        django-version: [ 3.1 ]
    env:
      DJANGO_VERSION: ${{ matrix.django-version }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2

#    - name: Install dependencies
#      run: python -m pip install --upgrade pip tox
#
#    - name: Test with tox
#      run: tox -e d${DJANGO_VERSION//.}-py${PYTHON_VERSION//.}

  release:
    if: github.event_name == 'pull_request' && startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - name: git
        run: |
            git --version
            echo "Slug variables"
            echo " - ${{ env.GITHUB_REF }}"
            echo " - ${{ env.GITHUB_REF_SLUG }}"
            echo " - ${{ env.GITHUB_HEAD_REF_SLUG }}"
            echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
            echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
            # output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
            echo "Slug URL variables"
            echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
            echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
            # output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
            echo "Short SHA variables"
            echo " - ${{ env.GITHUB_SHA_SHORT }}"
            # output e.g. : ffac537e
#            git config user.name "GitHub Actions Bot"
#            git config user.email "<>"
#            git checkout develop
#            git merge --no-ff github.ref
#            git branch -d  github.ref
